version: '3.1'
services:
  frontend:
    image: node:19
    volumes:
      - .:/app
    ports:
      - 3001:3000
    working_dir: /app
    command: tail -F log
  backend:
    image: node:19
    command: tail -F log