openapi: 3.0.3
info:
  title: book ticket
  description: ---
  version: 1.0.11
servers:
  - url: http://localhost:3008
tags:
  - name: ticket
    description: book tickets
paths:
  /book:
    post:
      tags:
        - ticket
      summary: book tickets
      requestBody:
        description: Update an existent pet in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TicketBook'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TicketSucess'          
        '400':
          description: Invalid ticket supplied
        '404':
          description: Ticket not found
        '422':
          description: Validation exception

components:
  schemas:
    TicketBook:
      required:
        - name
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        room_id:
          type: integer
          example: 1
        time_from:
          type: string
          example: '2024-07-06 10:00'
        time_end:
          type: string
          example: '2024-07-06 12:00'
        price:
          type: string
          example: 10
    TicketSucess:
      properties:
        id:
          type: integer
          format: int64
          example: 10
        code:
          type: string
          example: 123456789

